"""create_initial_tables

Revision ID: 80d6b1900072
Revises: 001
Create Date: 2026-03-05 20:14:55.561344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '80d6b1900072'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickers'))
    )
    op.create_index(op.f('ix_tickers_symbol'), 'tickers', ['symbol'], unique=True)
    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('accession_number', sa.String(length=25), nullable=False),
    sa.Column('doc_type', sa.String(length=10), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('period_of_report', sa.Date(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('is_chunked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_filings_ticker_id_tickers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_filings')),
    sa.UniqueConstraint('ticker_id', 'accession_number', name='uq_filings_ticker_accession')
    )
    op.create_index(op.f('ix_filings_ticker_id'), 'filings', ['ticker_id'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_news_articles_ticker_id_tickers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_articles')),
    sa.UniqueConstraint('ticker_id', 'url', name='uq_news_articles_ticker_url')
    )
    op.create_index(op.f('ix_news_articles_ticker_id'), 'news_articles', ['ticker_id'], unique=False)
    op.create_table('price_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_price_data_ticker_id_tickers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_data')),
    sa.UniqueConstraint('ticker_id', 'date', name='uq_price_data_ticker_date')
    )
    op.create_index(op.f('ix_price_data_ticker_id'), 'price_data', ['ticker_id'], unique=False)
    op.create_table('filing_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], name=op.f('fk_filing_chunks_filing_id_filings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_filing_chunks'))
    )
    op.create_index(op.f('ix_filing_chunks_filing_id'), 'filing_chunks', ['filing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filing_chunks_filing_id'), table_name='filing_chunks')
    op.drop_table('filing_chunks')
    op.drop_index(op.f('ix_price_data_ticker_id'), table_name='price_data')
    op.drop_table('price_data')
    op.drop_index(op.f('ix_news_articles_ticker_id'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_filings_ticker_id'), table_name='filings')
    op.drop_table('filings')
    op.drop_index(op.f('ix_tickers_symbol'), table_name='tickers')
    op.drop_table('tickers')
    # ### end Alembic commands ###
